---
- name: "Enable and start HAProxy"
  register: install_haproxy__service_status
  changed_when: install_haproxy__service_status.state != "started"
  ansible.builtin.service:
    name: "haproxy"
    state: "started"
    enabled: yes

- name: "Restart HAProxy"
  register: install_haproxy__service_status
  changed_when: install_haproxy__service_status.state != "restarted"
  ansible.builtin.service:
    name: "haproxy"
    state: "restarted"
    daemon_reload: true
