---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_haproxy"
      tags:
        - "labocbz.install_haproxy"
      vars:
        install_haproxy__path: "{{ inv_install_haproxy__path }}"
        install_haproxy__confs_path: "{{ inv_install_haproxy__confs_path }}"
        install_haproxy__error_path: "{{ inv_install_haproxy__error_path }}"
        install_haproxy__ssl_path: "{{ inv_install_haproxy__ssl_path }}"
        install_haproxy__error_files: "{{ inv_install_haproxy__error_files }}"
        install_haproxy__listen_stats: "{{ inv_install_haproxy__listen_stats }}"
        install_haproxy__listen_stats_port: "{{ inv_install_haproxy__listen_stats_port }}"
        install_haproxy__listen_stats_uri: "{{ inv_install_haproxy__listen_stats_uri }}"
        install_haproxy__stats_login: "{{ inv_install_haproxy__stats_login }}"
        install_haproxy__stats_password: "{{ inv_install_haproxy__stats_password }}"
        install_haproxy__listen_stats_https: "{{ inv_install_haproxy__listen_stats_https }}"
        install_haproxy__listen_stats_cert: "{{ inv_install_haproxy__listen_stats_cert }}"
        install_haproxy__listen_stats_key: "{{ inv_install_haproxy__listen_stats_key }}"
      ansible.builtin.include_role:
        name: "labocbz.install_haproxy"
